apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "name" . }}-pv
  labels:
    type: {{ template "name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  nfs:
    path: {{ .Values.persistence.nfs_path }}
    server: {{ .Values.persistence.nfs_server }}